//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node : IEntity<int>
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public NodeType NodeType { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime DeletedAt { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
