//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision : IEntity<int>
    {
        public Revision()
        {
            this.Nodes = new HashSet<Node>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string RID { get; set; }
        public string Message { get; set; }
        public string Author { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<Node> Nodes { get; set; }
        public virtual Project Project { get; set; }
    }
}
